In [2]:
import pandas as pd

In [3]:
D = pd.read_excel("https://github.com/junaart/ForStudents/raw/refs/heads/main/R/Zachet/DataSets/1.xlsx")

In [4]:
display(D)

,town1,Avg-Avg-Р41,Avg-Avg-Р42,Avg-Avg-Р43,Avg-Avg-Р44,Avg-Avg-Р51,Avg-Avg-Р52,Avg-Avg-Р53,Avg-Avg-Р61,Avg-Avg-Р62,Avg-Avg-Р63,Avg-Avg-Р64,Avg-Avg-Р71,Avg-Avg-Р72,Avg-Avg-Р7
0,Абакан,11.000000,4.000000,0.000000,69.500000,32.250000,12.500000,0.000000,54.250000,1.500000,0.0,0.000000,0.000000,0.000000,0.000000
1,Азовский район,0.666667,0.000000,1.000000,0.000000,1.666667,3.333333,0.000000,0.000000,21.000000,0.0,0.000000,0.000000,0.000000,0.000000
2,Аксайский район,3.250000,0.500000,5.500000,9.750000,2.500000,8.500000,0.000000,1.000000,36.500000,0.0,0.750000,1.000000,2070.750000,1.000000
3,Алексеевкий район,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
4,Анапа,0.500000,0.000000,0.000000,2.500000,1.000000,1.000000,0.000000,0.000000,0.500000,0.0,1.000000,6.500000,2160.350000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
276,Южно-Сахалинск,12.200000,0.400000,63.800000,7.550000,1.650000,2.150000,0.000000,1.150000,0.100000,0.0,0.500000,3.650000,3533.311500,1.200000
277,Якутск,10.266667,2.800000,3.050000,7.583333,11.566667,10.366667,0.083333,3.900000,1.300000,0.0,2.700000,7.183333,13601.792500,1.500000
278,Ялта,2.333333,3.833333,12.833333,17.000000,4.500000,13.166667,0.000000,0.000000,0.000000,0.0,0.000000,2.500000,819.333333,0.333333
279,Ярославль,43.964286,7.785714,0.142857,2.642857,18.178571,16.464286,0.285714,15.857143,5.535714,0.0,1.178571,24.142857,38921.410714,7.285714
280,Ярославский район,1.666667,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,3.333333,1.000000,0.0,0.000000,0.000000,0.000000,0.000000

In [5]:
import redis as rd

In [7]:
r=rd.Redis(host='localhost', db=0)
key = "Avg-Avg-Р41"
for i in range(len(D['Avg-Avg-Р41'])):
    r.set(key+str(i),str(D['Avg-Avg-Р41'].iloc[i]))

In [8]:
r=rd.Redis(host='localhost', db=0)
key = "Avg-Avg-Р42"
for i in range(len(D['Avg-Avg-Р42'])):
    r.set(key+str(i),str(D['Avg-Avg-Р42'].iloc[i]))

In [9]:
r=rd.Redis(host='localhost', db=0)
key = "Avg-Avg-Р43"
for i in range(len(D['Avg-Avg-Р43'])):
    r.set(key+str(i),str(D['Avg-Avg-Р43'].iloc[i]))

In [10]:
r=rd.Redis(host='localhost', db=0)
key = "Avg-Avg-Р44"
for i in range(len(D['Avg-Avg-Р44'])):
    r.set(key+str(i),str(D['Avg-Avg-Р44'].iloc[i]))

In [11]:
r=rd.Redis(host='localhost', db=0)
key = "Avg-Avg-Р51"
for i in range(len(D['Avg-Avg-Р51'])):
    r.set(key+str(i),str(D['Avg-Avg-Р51'].iloc[i]))

In [12]:
r=rd.Redis(host='localhost', db=0)
key = "Avg-Avg-Р53"
for i in range(len(D['Avg-Avg-Р53'])):
    r.set(key+str(i),str(D['Avg-Avg-Р53'].iloc[i]))

In [13]:
r=rd.Redis(host='localhost', db=0)
key = "Avg-Avg-Р61"
for i in range(len(D['Avg-Avg-Р61'])):
    r.set(key+str(i),str(D['Avg-Avg-Р61'].iloc[i]))

In [14]:
r=rd.Redis(host='localhost', db=0)
key = "Avg-Avg-Р62"
for i in range(len(D['Avg-Avg-Р62'])):
    r.set(key+str(i),str(D['Avg-Avg-Р62'].iloc[i]))

In [15]:
r=rd.Redis(host='localhost', db=0)
key = "Avg-Avg-Р63"
for i in range(len(D['Avg-Avg-Р63'])):
    r.set(key+str(i),str(D['Avg-Avg-Р63'].iloc[i]))

In [16]:
r=rd.Redis(host='localhost', db=0)
key = "Avg-Avg-Р64"
for i in range(len(D['Avg-Avg-Р64'])):
    r.set(key+str(i),str(D['Avg-Avg-Р64'].iloc[i]))

In [17]:
r=rd.Redis(host='localhost', db=0)
key = "Avg-Avg-Р71"
for i in range(len(D['Avg-Avg-Р71'])):
    r.set(key+str(i),str(D['Avg-Avg-Р71'].iloc[i]))

In [18]:
r=rd.Redis(host='localhost', db=0)
key = "Avg-Avg-Р772"
for i in range(len(D['Avg-Avg-Р72'])):
    r.set(key+str(i),str(D['Avg-Avg-Р72'].iloc[i]))

In [19]:
r=rd.Redis(host='localhost', db=0)
key = "Avg-Avg-Р7"
for i in range(len(D['Avg-Avg-Р7'])):
    r.set(key+str(i),str(D['Avg-Avg-Р7'].iloc[i]))