In [4]:
545+8656

9201

In [5]:
import redis as rd

In [6]:
r=rd.Redis(host='localhost', db=0)

In [7]:
dir(r)

['__abstractmethods__',
 '__annotations__',
 '__callable_proto_members_only__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__del__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__enter__',
 '__eq__',
 '__exit__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__parameters__',
 '__protocol_attrs__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_disconnect_raise',
 '_eval',
 '_evalsha',
 '_execute_command',
 '_fcall',
 '_georadiusgeneric',
 '_geosearchgeneric',
 '_is_protocol',
 '_is_runtime_protocol',
 '_send_command_parse_response',
 '_tfcall',
 '_zaggregate',
 '_zrange',
 'acl_cat',
 'acl_deluser',
 'acl_dryrun',
 'acl_genpass',
 'acl_getuser',
 'acl_help',
 'acl_list',
 'acl_load',
 'acl_log',
 'acl_log_reset',
 'acl_save',
 'acl_setuser',
 'acl_users',
 'acl_whoami',
 'append',
 'auth',
 'auto_close_connection_pool',
 'bf',
 'bgrewriteaof',
 'bgsave',
 'bitcount',
 'bitfield',
 'bitfield_ro',
 'bitop',
 'bitpos',
 'blmove',
 'blmpop',
 'blpop',
 'brpop',
 'brpoplpush',
 'bzmpop',
 'bzpopmax',
 'bzpopmin',
 'cf',
 'client',
 'client_getname',
 'client_getredir',
 'client_id',
 'client_info',
 'client_kill',
 'client_kill_filter',
 'client_list',
 'client_no_evict',
 'client_no_touch',
 'client_pause',
 'client_reply',
 'client_setinfo',
 'client_setname',
 'client_tracking',
 'client_tracking_off',
 'client_tracking_on',
 'client_trackinginfo',
 'client_unblock',
 'client_unpause',
 'close',
 'cluster',
 'cms',
 'command',
 'command_count',
 'command_docs',
 'command_getkeys',
 'command_getkeysandflags',
 'command_info',
 'command_list',
 'config_get',
 'config_resetstat',
 'config_rewrite',
 'config_set',
 'connection',
 'connection_pool',
 'copy',
 'dbsize',
 'debug_object',
 'debug_segfault',
 'decr',
 'decrby',
 'delete',
 'dump',
 'echo',
 'eval',
 'eval_ro',
 'evalsha',
 'evalsha_ro',
 'execute_command',
 'exists',
 'expire',
 'expireat',
 'expiretime',
 'failover',
 'fcall',
 'fcall_ro',
 'flushall',
 'flushdb',
 'from_pool',
 'from_url',
 'ft',
 'function_delete',
 'function_dump',
 'function_flush',
 'function_kill',
 'function_list',
 'function_load',
 'function_restore',
 'function_stats',
 'geoadd',
 'geodist',
 'geohash',
 'geopos',
 'georadius',
 'georadiusbymember',
 'geosearch',
 'geosearchstore',
 'get',
 'get_cache',
 'get_connection_kwargs',
 'get_encoder',
 'get_retry',
 'getbit',
 'getdel',
 'getex',
 'getrange',
 'getset',
 'graph',
 'hdel',
 'hello',
 'hexists',
 'hexpire',
 'hexpireat',
 'hexpiretime',
 'hget',
 'hgetall',
 'hincrby',
 'hincrbyfloat',
 'hkeys',
 'hlen',
 'hmget',
 'hmset',
 'hpersist',
 'hpexpire',
 'hpexpireat',
 'hpexpiretime',
 'hpttl',
 'hrandfield',
 'hscan',
 'hscan_iter',
 'hset',
 'hsetnx',
 'hstrlen',
 'httl',
 'hvals',
 'incr',
 'incrby',
 'incrbyfloat',
 'info',
 'json',
 'keys',
 'lastsave',
 'latency_doctor',
 'latency_graph',
 'latency_histogram',
 'latency_history',
 'latency_latest',
 'latency_reset',
 'lcs',
 'lindex',
 'linsert',
 'llen',
 'lmove',
 'lmpop',
 'load_external_module',
 'lock',
 'lolwut',
 'lpop',
 'lpos',
 'lpush',
 'lpushx',
 'lrange',
 'lrem',
 'lset',
 'ltrim',
 'memory_doctor',
 'memory_help',
 'memory_malloc_stats',
 'memory_purge',
 'memory_stats',
 'memory_usage',
 'mget',
 'migrate',
 'module_list',
 'module_load',
 'module_loadex',
 'module_unload',
 'monitor',
 'move',
 'mset',
 'msetnx',
 'object',
 'parse_response',
 'persist',
 'pexpire',
 'pexpireat',
 'pexpiretime',
 'pfadd',
 'pfcount',
 'pfmerge',
 'ping',
 'pipeline',
 'psetex',
 'psync',
 'pttl',
 'publish',
 'pubsub',
 'pubsub_channels',
 'pubsub_numpat',
 'pubsub_numsub',
 'pubsub_shardchannels',
 'pubsub_shardnumsub',
 'quit',
 'randomkey',
 'readonly',
 'readwrite',
 'register_script',
 'rename',
 'renamenx',
 'replicaof',
 'reset',
 'response_callbacks',
 'restore',
 'role',
 'rpop',
 'rpoplpush',
 'rpush',
 'rpushx',
 'sadd',
 'save',
 'scan',
 'scan_iter',
 'scard',
 'script_debug',
 'script_exists',
 'script_flush',
 'script_kill',
 'script_load',
 'sdiff',
 'sdiffstore',
 'select',
 'sentinel',
 'sentinel_ckquorum',
 'sentinel_failover',
 'sentinel_flushconfig',
 'sentinel_get_master_addr_by_name',
 'sentinel_master',
 'sentinel_masters',
 'sentinel_monitor',
 'sentinel_remove',
 'sentinel_reset',
 'sentinel_sentinels',
 'sentinel_set',
 'sentinel_slaves',
 'set',
 'set_response_callback',
 'set_retry',
 'setbit',
 'setex',
 'setnx',
 'setrange',
 'shutdown',
 'sinter',
 'sintercard',
 'sinterstore',
 'sismember',
 'slaveof',
 'slowlog_get',
 'slowlog_len',
 'slowlog_reset',
 'smembers',
 'smismember',
 'smove',
 'sort',
 'sort_ro',
 'spop',
 'spublish',
 'srandmember',
 'srem',
 'sscan',
 'sscan_iter',
 'stralgo',
 'strlen',
 'substr',
 'sunion',
 'sunionstore',
 'swapdb',
 'sync',
 'tdigest',
 'tfcall',
 'tfcall_async',
 'tfunction_delete',
 'tfunction_list',
 'tfunction_load',
 'time',
 'topk',
 'touch',
 'transaction',
 'ts',
 'ttl',
 'type',
 'unlink',
 'unwatch',
 'wait',
 'waitaof',
 'watch',
 'xack',
 'xadd',
 'xautoclaim',
 'xclaim',
 'xdel',
 'xgroup_create',
 'xgroup_createconsumer',
 'xgroup_delconsumer',
 'xgroup_destroy',
 'xgroup_setid',
 'xinfo_consumers',
 'xinfo_groups',
 'xinfo_stream',
 'xlen',
 'xpending',
 'xpending_range',
 'xrange',
 'xread',
 'xreadgroup',
 'xrevrange',
 'xtrim',
 'zadd',
 'zcard',
 'zcount',
 'zdiff',
 'zdiffstore',
 'zincrby',
 'zinter',
 'zintercard',
 'zinterstore',
 'zlexcount',
 'zmpop',
 'zmscore',
 'zpopmax',
 'zpopmin',
 'zrandmember',
 'zrange',
 'zrangebylex',
 'zrangebyscore',
 'zrangestore',
 'zrank',
 'zrem',
 'zremrangebylex',
 'zremrangebyrank',
 'zremrangebyscore',
 'zrevrange',
 'zrevrangebylex',
 'zrevrangebyscore',
 'zrevrank',
 'zscan',
 'zscan_iter',
 'zscore',
 'zunion',
 'zunionstore']

In [8]:
r.get("a")

b'785'

In [9]:
int(r.get("a"))

785

In [10]:
r.set("a",'666')

True

In [11]:
r.keys()

[b'd', b'a', b'g', b'b', b'c']

In [12]:
r.rpush("g",1)

2

In [13]:
r.lrange("g", 0, -1)

[b'1', b'1']

In [14]:
import pandas as pd

In [15]:
D = pd.read_csv("https://github.com/junaart/ForStudents/raw/refs/heads/main/R/Lesson_2/demo.csv",sep=";")

In [16]:
display(D)

,Год,1990,1995,2000,2001,2002,2003,2004,2005,2006,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Все население,69.19,64.52,65.34,65.23,64.95,64.84,65.31,65.37,66.69,...,68.94,69.831495,70.24,70.76,70.93,71.39,71.87,72.70,72.91,73.34
1,Все мужчины,63.73,58.12,59.03,58.92,58.68,58.53,58.91,58.92,60.43,...,63.09,64.039883,64.56,65.13,65.29,65.92,66.50,67.51,67.75,68.24
2,Все женщины,74.30,71.59,72.26,72.17,71.90,71.85,72.36,72.47,73.34,...,74.88,75.605552,75.86,76.30,76.47,76.71,77.06,77.64,77.82,78.17
3,Все городское население,69.55,64.70,65.69,65.57,65.40,65.36,65.87,66.10,67.43,...,69.69,70.509150,70.83,71.33,71.44,71.91,72.35,73.16,73.34,73.72
4,Все городское население мужчины,64.31,58.30,59.35,59.23,59.09,59.01,59.42,59.58,61.12,...,63.82,64.668980,65.10,65.64,65.75,66.38,66.91,67.90,68.11,68.56
5,Все городское население женщины,74.34,71.64,72.46,72.37,72.18,72.20,72.73,72.99,73.88,...,75.39,76.103459,76.27,76.70,76.83,77.09,77.38,77.96,78.09,78.41
6,Все сельское население,67.97,63.99,64.34,64.25,63.68,63.34,63.77,63.45,64.74,...,66.92,67.994370,68.61,69.18,69.49,69.90,70.50,71.38,71.67,72.21
7,Все сельское население мужчины,62.03,57.64,58.14,58.07,57.54,57.20,57.56,57.22,58.69,...,61.19,62.399606,63.12,63.75,64.07,64.67,65.36,66.43,66.75,67.36
8,Все сельское население женщины,73.95,71.40,71.66,71.57,71.09,70.81,71.27,71.06,71.86,...,73.42,74.208291,74.66,75.13,75.43,75.59,76.07,76.66,76.93,77.39

In [17]:
S = pd.read_excel("https://github.com/junaart/ForStudents/raw/refs/heads/main/R/Lesson_2/demo.xlsx")
display(S)

,Год,1990,1995,2000,2001,2002,2003,2004,2005,2006,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Все население,69.19,64.52,65.34,65.23,64.95,64.84,65.31,65.37,66.69,...,68.94,69.831495,70.24,70.76,70.93,71.39,71.87,72.70,72.91,73.34
1,Все мужчины,63.73,58.12,59.03,58.92,58.68,58.53,58.91,58.92,60.43,...,63.09,64.039883,64.56,65.13,65.29,65.92,66.50,67.51,67.75,68.24
2,Все женщины,74.30,71.59,72.26,72.17,71.90,71.85,72.36,72.47,73.34,...,74.88,75.605552,75.86,76.30,76.47,76.71,77.06,77.64,77.82,78.17
3,Все городское население,69.55,64.70,65.69,65.57,65.40,65.36,65.87,66.10,67.43,...,69.69,70.509150,70.83,71.33,71.44,71.91,72.35,73.16,73.34,73.72
4,Все городское население мужчины,64.31,58.30,59.35,59.23,59.09,59.01,59.42,59.58,61.12,...,63.82,64.668980,65.10,65.64,65.75,66.38,66.91,67.90,68.11,68.56
5,Все городское население женщины,74.34,71.64,72.46,72.37,72.18,72.20,72.73,72.99,73.88,...,75.39,76.103459,76.27,76.70,76.83,77.09,77.38,77.96,78.09,78.41
6,Все сельское население,67.97,63.99,64.34,64.25,63.68,63.34,63.77,63.45,64.74,...,66.92,67.994370,68.61,69.18,69.49,69.90,70.50,71.38,71.67,72.21
7,Все сельское население мужчины,62.03,57.64,58.14,58.07,57.54,57.20,57.56,57.22,58.69,...,61.19,62.399606,63.12,63.75,64.07,64.67,65.36,66.43,66.75,67.36
8,Все сельское население женщины,73.95,71.40,71.66,71.57,71.09,70.81,71.27,71.06,71.86,...,73.42,74.208291,74.66,75.13,75.43,75.59,76.07,76.66,76.93,77.39

In [18]:
D["1990"]

0    69.19
1    63.73
2    74.30
3    69.55
4    64.31
5    74.34
6    67.97
7    62.03
8    73.95
Name: 1990, dtype: float64

In [19]:
D["1990"][0]

np.float64(69.19)

In [20]:
str(D["1990"][0])

'69.19'

In [22]:
D.iloc[0,]

Год     Все население
1990            69.19
1995            64.52
2000            65.34
2001            65.23
2002            64.95
2003            64.84
2004            65.31
2005            65.37
2006            66.69
2007            67.61
2008            67.99
2009            68.78
2010            68.94
2011        69.831495
2012            70.24
2013            70.76
2014            70.93
2015            71.39
2016            71.87
2017             72.7
2018            72.91
2019            73.34
Name: 0, dtype: object

In [23]:
D.iloc[0,0]

'Все население'

In [25]:
D.iloc[:,0]

0                      Все население
1                        Все мужчины
2                        Все женщины
3            Все городское население
4    Все городское население мужчины
5    Все городское население женщины
6             Все сельское население
7     Все сельское население мужчины
8     Все сельское население женщины
Name: Год, dtype: object

In [26]:
D.iloc[0,]

Год     Все население
1990            69.19
1995            64.52
2000            65.34
2001            65.23
2002            64.95
2003            64.84
2004            65.31
2005            65.37
2006            66.69
2007            67.61
2008            67.99
2009            68.78
2010            68.94
2011        69.831495
2012            70.24
2013            70.76
2014            70.93
2015            71.39
2016            71.87
2017             72.7
2018            72.91
2019            73.34
Name: 0, dtype: object

In [ ]:
for i in range(len(D["1990"])):
    print(str(D["1990"].iloc[i]))

69.19
63.73
74.3
69.55
64.31
74.34
67.97
62.03
73.95

In [32]:
r = rd.Redis()
key = "my"
for i in range(len(D["1990"])):
    r.set(key+str(i),str(D["1990"].iloc[i]))

In [33]:
r.get("my0")

b'69.19'